project:
  type: website
  output-dir: docs

website:
  title: "首页"
  navbar:
    left:
      - categories.qmd
    right:
      - about.qmd
      - resume.qmd
  

format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

