project:
  type: website
  output-dir: docs

website:
  title: "首页"
  navbar:
    left:
      - categories.qmd
    right:
      - about.qmd
      - resume.qmd
  
  

format:
  html:
    theme: litera
    monobackgroundcolor: rgb(255,255,248)
    linestretch: 1.6
    css: styles.css
    toc: true
    linkcolor: rgb(50,140,210)
    published-title: 日期
    author-title: 作者
    mainfont: fangsong
    
    

editor: visual

