project:
  type: website
  output-dir: docs

website:
  title: "首页"
  reader-mode: true
  navbar:
    left:
      - categories.qmd
    right:
      - about.qmd
      - resume.qmd
  page-footer: 
    center: "Copyright © fhaoshao 2023, license:[CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)."


    
  
  

format:
  html:
    theme: litera
    backgroundcolor: rgb(251,252,250)
    title-block-banner: rgb(251,252,250)
    linestretch: 1.6
    fontsize: 15px
    css: styles.css
    margin-top: 3em
    toc: true
    linkcolor: rgb(50,140,210)
    published-title: 日期
    author-title: 作者
    mainfont: Source Han Serif
    grid:
      sidebar-width: 200px
      body-width: 750px
      margin-width: 300px
      gutter-width: 1.5rem
    
    

editor: visual

