---
title: "写在写博客前"
date: "2023-07-27"
description: "无厘头地乱写一通 莫当信言"
title-block-banner: rgb(249,250,247)
date-format: short
categories: [其它]
draft: true
---

------------------------------------------------------------------------

八月份在家里算是彻彻底底地闲了下来。但闲久了实在是无聊，也无什么人可聊，又不想随便地变得有聊，更不想变忙，就只能找点有趣的事干了，正所谓"有聊的人不一定有趣，有趣的人一定不会无聊"。于是我开始清理电脑文件。在清理电脑文件的途中，我又开始折腾起来了Rmarkdown，就发现了blogdown。这是Rmarkdown的作者谢益辉开发出来给自己写博客用的R包。后来顺藤摸瓜看了一大串别人的博客，我发现写博客的人都很有意思，就萌生了搭建博客的想法。

::: column-margin
以前一直觉得，妈的只有那些最无聊的人才会整天想着找别人聊天，要不就是没事干想给你找事干，成天问你干嘛干嘛的。现在看来是有些绝情了。哈哈哈哈哈哈！
:::

博客是个舶来词，即Bolg（Web log），直译过来就是网络日志，像微博、博主、Plog、Vlog这些网络概念都是由博客延申而来。博客对于现在的人们应该挺陌生的，毕竟在中国这东西火的时候是差不多二十年前。虽然说但博客并不是消失了，只是这个名字现在不太容易被看见，因为其概念和内容都已经随着移动互联网全民上网时代的到来被解构了，分散到了各个社交媒体平台。写东西记录分享的人一直都在，想分享爱好日常吐吐槽的可以发微博、朋友圈和小红书，想写文章赚流量的可以去写公众号、小红书和知乎专栏，想结交网友的现在交友软件也是一大堆。

广义上讲，这些在互联网上分享内容的平台账号，其实都可以算是博客，况且博主这个称谓也一直都在用。但是，相较于传统互联网的那个以人为本的时代，现在的移动互联网已经变成了流量至上。因为能上网的人越来越多，人多了就变成了流量，有流量就方便赚钱。正所谓赚钱发财的捷径就是让每个人都给你一块钱，这就是流量的意义，乞丐都知道的道理。在这个流量至上的时代，安心地当个消费者也挺好，毕竟大脑按摩多爽啊！脑子用多了之后就看看小说打打游戏刷刷剧，你个人想写点东西的话就像互联网生态中的稀有种，很难被别人看到如果说把这些社交媒体平台比作商品房，有不同的定位和标签，那么个人博客就是你自家的宅基地。

大二的大多数时候都过得比较烦，

想要绞尽脑汁地写点东西，却发现自己脑袋里全是豆腐渣，愣是挤不出一点汁来

我总是把心事揉成一团，然后攥在手里，越攥越紧，打死也不肯给别人看。后来展开来一看，我的心事是一张揉皱了的的白纸，上面什么也没写。
