---
title: "上半年回顾"
description: "个人情绪比较多，请谨慎阅读！！！"
date: "2023-08-19"
title-block-banner: rgb(249,250,247)
date-format: short
categories: [其它]
draft: true
---

------------------------------------------------------------------------
我几乎不向外表达我的内心情绪，

上半年的精神状态比较差，大概就是处于一种不知道该干嘛和什么事都不想干的状态。因为很多事情都是些无所谓的烦心事，诸如密不透风的课表、抄不完的实验报告、乱七八糟的竞赛，还有三更半夜不关灯的室友等等。正是因为了没有了所谓，才叫人感到心烦,烦完了之后就只剩下哀伤了。我开始成天阴暗地躺在床上苦大仇深地胡思乱想。唉！既然我每天经历的一切都于我无谓，那么我能于什么有谓呢？日子一天天得过去，不过是在虚无中寻找忙碌，然后在真实中感到无助罢了。想得越多，就越发现自己在变轻，繁杂的思绪把我充成了一个氢气球。我开始摆脱引力，飞向大气，然后飞着飞着就爆了。有时候挺羡慕周围那些鸭梨山大的同学的，鸭梨山大好啊，起码能让自己感觉是重的。这是一种不莫名的哀伤，至于这些事情为什么会变得无谓，我只能责怪自己

  最悲观的时候甚至觉得大学就是在虚无中寻找忙碌，然后在真实中感到无助。。很难具体地说我那时经历了什么，只能抽象地描述，我经历了与大学评价体系脱节和社交需求关系缺失造成的自我价值崩溃。

  

  庆幸的是，我还能有一个和我一样窝囊的朋友，。我得感谢他们

  惶惶不可终日，怏怏何须一生！以后还是得过得踏实一点，得对未来有个期望，起码不能饿死。

  暑假在家里呆久了实在无聊，也无人可聊，但又不想随便地变得"有聊"，只能找点有趣的事干了，毕竟有聊的人不一定有趣，有趣的人一定不会无聊。我开始

  说起无聊，以前总是觉得，妈的只有那些最无聊的人才会整天想着找别人聊天，成天没事想着给别人找事干，天天问你干嘛干嘛。我非常鄙视这种人。后来我就真的成了一个"无聊"的人。所谓无聊，就是没有聊天。但是我就是不喜欢找别人聊天，去找别人聊天，那我不就是变成了我之前所鄙视的最无聊的人？

于是我成了个名副其实的最无聊的人。那怎么办，我岂不是要当一辈子无聊的人了？我只能胡思乱想，然后开始苦大仇深地胡思乱想。因为有聊的人不一定有趣，但是有趣的人一定不会无聊。

我写博客是为了装逼。装逼这件事，说好听点叫展示价值，说专业一点属于社交管理。劳资太久没装逼了。

七月末我在清理电脑文件，然后又开始折腾起了Rstudio，因为我在上学期干生科赛项目的时候用的是Rmarkdown来写实验记录，觉得Rmarkdown这个东西发现了bolgdown这个项目 人活着总是要打开一扇窗的，有些东西就是要给别人看。家徒四壁才能顶天立地。

我一直觉得，爱是人类社会的内含子。现在的功利社会就是让人一直去翻译蛋白质
